version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - canal-network

  canal-server:
    image: canal/canal-server:v1.1.7
    container_name: canal
    ports:
      - "11111:11111"
    environment:
      - canal.instance.master.address=host.docker.internal:3306
      - canal.instance.dbUsername=canal
      - canal.instance.dbPassword=canal
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
    networks:
      - canal-network


  kibana:
    image: kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - canal-network



networks:
  canal-network:
    driver: bridge